version: "3"
services:

  back-end:
    container_name: back-end
    build: "./back-end"
    restart: on-failure
    volumes:
      - ./back-end:/back-end
    ports:
      - "8443:8443"

networks:
  local:
    driver: bridge
