version: "3"
services:

  back-end:
    container_name: back-end
    build: "./back-end"
    restart: on-failure
    volumes:
      - ./back-end:/back-end
    ports:
      - "8443:8443"
  
  front-end:
    container_name: front-end
    build: "./front-end"
    restart: on-failure
    volumes:
      - ./front-end:/front-end
    ports:
      - "3000:3000"

networks:
  local:
    driver: bridge
