FROM python:3.9.5

WORKDIR /back-end

COPY . .

RUN apt-get update -y && apt-get upgrade -y

RUN pip install -r requirements.txt

EXPOSE 8443

CMD [ "python", "./chatFlow/manage.py", "runserver", "0.0.0.0:8443" ]
