FROM python:3.9.5

WORKDIR /back-end

COPY . .

RUN apt-get update -y && apt-get upgrade -y && chmod +x ./start.sh

RUN pip install -r requirements.txt

RUN pip install -q -U google-generativeai

RUN ./start.sh

# ENV PYTHONUNBUFFERED=1

EXPOSE 8443

CMD ["daphne", "-p", "8443", "-b", "0.0.0.0", "chatFlow.asgi:application"]
