FROM python:3.9.5

WORKDIR /back-end

COPY . .

RUN apt-get update -y && apt-get upgrade -y && chmod +x ./start.sh

RUN pip install -r requirements.txt

RUN ./start.sh

# ENV PYTHONUNBUFFERED=1

EXPOSE 8443

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8443" ]
